name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0
dependencies:
  flutter:
    sdk: flutter
  # Hemos dejado solo una versión de cada una y corregido la sangría
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.0
  firebase_auth: ^4.7.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
lutter:
  uses-material-design: true 