// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTGOchUMCf55SdUxY-jVH-8i2BxDeeFwY',
    appId: '1:867118322470:web:ff805da24c495f2cd5a7e7',
    messagingSenderId: '867118322470',
    projectId: 'reposteriaproyecto-4f2d7',
    authDomain: 'reposteriaproyecto-4f2d7.firebaseapp.com',
    storageBucket: 'reposteriaproyecto-4f2d7.firebasestorage.app',
    measurementId: 'G-SX8180K29J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvrTF11mRJs66MbCWDgMVy_ZTc1m2LeQM',
    appId: '1:867118322470:android:1cdc1e5898ff9761d5a7e7',
    messagingSenderId: '867118322470',
    projectId: 'reposteriaproyecto-4f2d7',
    storageBucket: 'reposteriaproyecto-4f2d7.firebasestorage.app',
  );
}
